name: Build and push Docker image - gdlfsamuelemmanuel

on:
  push:
    branches:
      - maven
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Usa el contexto actual
          push: true  # Ahora necesitamos subir la imagen
          tags: 'gdlcemmanuelsamuel.azurecr.io/petclinic-app:v1'
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


